stages:
  - build
  - test
  - dockerize
  - deploy

cache:
  key:
    files:
      - yarn.lock
  paths:
    - node_modules

build:
  image: node:lts-alpine
  stage: build
  script:
    - yarn install
    - yarn build
  artifacts:
    paths:
      - "dist"

test:
  image: node:lts-alpine
  stage: test
  script:
    - yarn install
    - yarn test:unit


dockerize:
  stage: dockerize
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"${CI_REGISTRY}\":{\"auth\":\"$(printf "%s:%s" "${CI_REGISTRY_USER}" "${CI_REGISTRY_PASSWORD}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
    - >-
      /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}:latest"
  needs:
    - build


deploy:
  stage: deploy
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install faraday -v 1.10.0
    - gem install dpl
    - dpl --provider=heroku --app=fe-todo-assignment-mbakin --api-key=$HEROKU_API_KEY
  environment:
    name: Staging
    url: https://fe-todo-assignment-mbakin.herokuapp.com/
  only:
    - master
